"""delete nullable for password

Revision ID: 33970f366b57
Revises: d1460cdab613
Create Date: 2019-10-29 23:18:05.871245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33970f366b57'
down_revision = 'd1460cdab613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
